name: dunya_evim
description: Dünya Benim Evim

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  image_picker: ^0.8.7
  path_provider: ^2.0.14
  firebase_storage: ^11.0.16
  carousel_slider: ^4.2.1
  currency_text_input_formatter: ^2.1.8
  shared_preferences: ^2.0.20
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  geocoding: ^2.1.0
  geocoder2: ^1.4.0
  url_launcher: ^6.1.10
  easy_localization: ^3.0.2
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.3.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_image_compress: ^1.1.3
  firebase_app_check: ^0.1.1+14
  huawei_hmsavailability: ^6.6.0+300
  huawei_location: ^6.4.0+300
  huawei_map: ^6.5.0+301
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar: ^5.0.2
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  photo_view: ^0.14.0
  lottie: ^2.4.0
  country_code_picker: ^3.0.0
  firebase_crashlytics: ^3.3.3




dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
# flutter_native_splash:
#   color: "#000000"
#   image: assets/images/dunya_evim_logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translation/
  fonts:
     - family: Kalam
       fonts:
         - asset: fonts/Kalam-Regular.ttf
     - family: SourceSansPro
       fonts:
         - asset: fonts/SourceSansPro-SemiBold.ttf

