// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCxrCTna6brly6sy50C5I2SVyL5pAlWDw',
    appId: '1:956578692336:web:04d67cbb63ee9497491635',
    messagingSenderId: '956578692336',
    projectId: 'dunya-evim',
    authDomain: 'dunya-evim.firebaseapp.com',
    storageBucket: 'dunya-evim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD758rGeFnz1kWQj5tVWx9GNzRAl3z31dU',
    appId: '1:956578692336:android:9ed87b743e63d91f491635',
    messagingSenderId: '956578692336',
    projectId: 'dunya-evim',
    storageBucket: 'dunya-evim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0oQDKnSgY5_0CI1PERy1pdlBIic3rCrs',
    appId: '1:956578692336:ios:87a65316ef64dc09491635',
    messagingSenderId: '956578692336',
    projectId: 'dunya-evim',
    storageBucket: 'dunya-evim.appspot.com',
    androidClientId: '956578692336-llhhv65ikgoa8icsq93ot1atdd2q6ks1.apps.googleusercontent.com',
    iosClientId: '956578692336-djktcila55te350t4k2ls4dd0m13k7ma.apps.googleusercontent.com',
    iosBundleId: 'com.dunyaevim.dunyaEvim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0oQDKnSgY5_0CI1PERy1pdlBIic3rCrs',
    appId: '1:956578692336:ios:87a65316ef64dc09491635',
    messagingSenderId: '956578692336',
    projectId: 'dunya-evim',
    storageBucket: 'dunya-evim.appspot.com',
    androidClientId: '956578692336-llhhv65ikgoa8icsq93ot1atdd2q6ks1.apps.googleusercontent.com',
    iosClientId: '956578692336-djktcila55te350t4k2ls4dd0m13k7ma.apps.googleusercontent.com',
    iosBundleId: 'com.dunyaevim.dunyaEvim',
  );
}
